// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUserName.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFeed = `-- name: GetUserFeed :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) GetUserFeed(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserFeed, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
